### ISSUE TITLE
[Question] Contact

### ISSUE THREAD

**Issue by noraj** [mitre-cyber-academy/ctf-scoreboard-archive#46]
What is the best place to talk with you about this CTF platform?

I see that the MITRE cyber academy mail is `mitre.tpalab@gmail.com` but this is may be not teh best place to talk.

Have you a public IRC channel, slack or gitter chat or whatever? Because actually the only way to talk to you is through the MITRE mail or issue.

**Comment by rbclark** [comment]
We are re-working a large number of parts of our system this year, we normally use an IRC chat however we are planning to move away from that this year to Discord. That being said we have not setup the Discord channel yet and we do not monitor the IRC channel year round. We do monitor the email ctf [at] mitre [dot] org regularly.

**Comment by rbclark** [comment]
We have now moved all of our communication over to discord: http://mitrecyberacademy.org/contact/
